name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03
        ports:
          - 8000:8000
        options: >-
          --mount type=volume,source=sail-mysql,target=/var/lib/mysql
          --mount type=volume,source=sail-redis,target=/data
        healthcheck:
          test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8000/health"]
          interval: 30s
          retries: 3
          start_period: 1m
          timeout: 10s

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, xml, pdo, pdo_mysql
          ini-values: post_max_size=256M, max_execution_time=180

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run Laravel Sail
        run: |
          docker-compose -f docker-compose.yml up -d
          docker-compose -f docker-compose.yml exec -T laravel.test composer install
          docker-compose -f docker-compose.yml exec -T laravel.test php artisan key:generate
          docker-compose -f docker-compose.yml exec -T laravel.test php artisan migrate --force
        env:
          DB_PASSWORD: password
          DB_DATABASE: laravel
          DB_USERNAME: sail

      - name: Run tests
        run: docker-compose -f docker-compose.yml exec -T laravel.test php artisan test --coverage
        env:
          DB_PASSWORD: password
          DB_DATABASE: laravel
          DB_USERNAME: sail

      - name: Upload coverage to GitHub
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
