name: Run PHPUnit Tests

on:
  workflow_call:
  push:
    branches-ignore:
      - main

jobs:
  run-phpunit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Wait for MySQL to be ready
        run: |
          docker-compose exec mysql bash -c 'until mysqladmin ping -h "localhost" --silent; do sleep 1; done'

      - name: Prepare Application
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan doctrine:generate:proxies
          php artisan storage:link
          php artisan migrate --seed

      - name: PHPUnit
        run: php artisan test --parallel --coverage-clover=coverage.xml
      - uses: codecov/codecov-action@v4
        env:
          DB_PASSWORD: password
          DB_DATABASE: laravel
          DB_USERNAME: sail
      - name: Tear down Docker Compose
        if: always()
        run: docker-compose down
