name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, xml, pdo, pdo_mysql
          ini-values: post_max_size=256M, max_execution_time=180

      - name: Build and run Laravel Sail
        run: |
          docker-compose -f docker-compose.yml up -d
          docker-compose -f docker-compose.yml exec -T laravel.test composer install
          docker-compose -f docker-compose.yml exec -T laravel.test php artisan key:generate
          docker-compose -f docker-compose.yml exec -T laravel.test php artisan migrate --force
        env:
          DB_PASSWORD: password
          DB_DATABASE: laravel
          DB_USERNAME: sail

      - name: Run tests
        run: docker-compose -f docker-compose.yml exec -T laravel.test php artisan test --coverage
        env:
          DB_PASSWORD: password
          DB_DATABASE: laravel
          DB_USERNAME: sail

      - name: Upload coverage to GitHub
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
